"""
Module A2 — Blast Radius Estimation (Option A)

Builds a NetworkX graph of the synthetic infra dependency topology
(app -> db -> server, plus same-VPC clustering) generated by the simulator,
with controls attached to the system they govern. For a compound incident,
BFS out from the affected systems to answer: "which other systems/data are
exposed by this combined drift?" — weighted by hop distance and each
system's control criticality (production controls count for more than dev).
"""
import json
import networkx as nx
from sqlalchemy.orm import Session

from database.models import Control, SystemDependency, Incident

ENV_WEIGHT = {"production": 3.0, "staging": 1.5, "dev": 1.0}
MAX_HOPS = 2
HOP_DECAY = 0.5  # each additional hop counts for half as much


def build_infra_graph(session: Session) -> nx.Graph:
    g = nx.Graph()

    controls = session.query(Control).all()
    for c in controls:
        g.add_node(c.system_instance, kind="system")
        g.add_edge(
            c.control_id, c.system_instance,
            relation="governs", weight=1.0,
        )
        g.add_node(c.control_id, kind="control", environment=c.environment,
                   category=c.category, domain=c.domain)

    deps = session.query(SystemDependency).all()
    for d in deps:
        g.add_node(d.source_system, kind="system")
        g.add_node(d.target_system, kind="system")
        g.add_edge(d.source_system, d.target_system, relation=d.relation, weight=1.0)

    return g


def _controls_on_system(controls_by_instance, system_instance):
    return controls_by_instance.get(system_instance, [])


def estimate_blast_radius(session: Session, incident: Incident, graph: nx.Graph = None):
    if graph is None:
        graph = build_infra_graph(session)

    controls = session.query(Control).all()
    controls_by_id = {c.control_id: c for c in controls}
    controls_by_instance = {}
    for c in controls:
        controls_by_instance.setdefault(c.system_instance, []).append(c)

    origin_control_ids = json.loads(incident.controls_involved or "[]")
    origin_systems = {
        controls_by_id[cid].system_instance
        for cid in origin_control_ids if cid in controls_by_id
    }

    exposed_systems = {}  # system_instance -> min hop distance
    for origin in origin_systems:
        if origin not in graph:
            continue
        lengths = nx.single_source_shortest_path_length(graph, origin, cutoff=MAX_HOPS)
        for node, hop in lengths.items():
            if graph.nodes.get(node, {}).get("kind") != "system":
                continue
            if node in origin_systems and hop == 0:
                continue
            if node not in exposed_systems or hop < exposed_systems[node]:
                exposed_systems[node] = hop

    blast_score = 0.0
    exposure_detail = []
    for system, hop in exposed_systems.items():
        attached = _controls_on_system(controls_by_instance, system)
        if not attached:
            continue
        env_weight = max((ENV_WEIGHT.get(c.environment, 1.0) for c in attached), default=1.0)
        decay = HOP_DECAY ** hop
        contribution = env_weight * len(attached) * decay
        blast_score += contribution
        exposure_detail.append({
            "system": system,
            "hops_away": hop,
            "controls_attached": len(attached),
            "max_environment_weight": env_weight,
        })

    exposure_detail.sort(key=lambda x: (x["hops_away"], -x["controls_attached"]))

    incident.blast_radius_score = round(blast_score, 1)
    incident.blast_radius_systems = json.dumps(exposure_detail[:25])
    incident.blast_radius_hops = MAX_HOPS
    session.commit()

    return {
        "blast_radius_score": incident.blast_radius_score,
        "exposed_systems": exposure_detail,
        "origin_systems": list(origin_systems),
    }


def estimate_all_incidents(session: Session):
    graph = build_infra_graph(session)
    incidents = session.query(Incident).filter(
        (Incident.blast_radius_score.is_(None)) | (Incident.blast_radius_score == 0.0)
    ).all()
    results = []
    for inc in incidents:
        results.append(estimate_blast_radius(session, inc, graph=graph))
    return {"incidents_processed": len(results)}
